Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/publication_listings_controller.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/controllers/publication_listings_controller.rb'
