language: ruby

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x xvfb"
  - "gem --version"
  - "gem update --system"
  - "gem --version"
  - "gem install bundler"
  - 'gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"'

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/activity_insight.yml.travis config/activity_insight.yml"
  - "cp config/integration_passcode.yml.travis config/integration_passcode.yml"
  - "mkdir app/parsing_files"

script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:test:load"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rspec"

services:
  - mysql

addons:
  mariadb: '10.2'

