version: '3.3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PW}
    image: mariadb:10.3
    ports:
    - "3306:3306"
    volumes:
    - ai-integration-data:/var/lib/mysql
  web:
    image: app:${IMG_TAG}
    environment:
      # RAILS_ENV: production # The startup script defaults to development, change to production if need be
      MYSQL_HOST: db
      MYSQL_PASSWORD: ${DATABASE_PW}      
    # Explicit build context for Dockerfile, can be shortened to -> build: .
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
    - db
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      consistency: cached
      source: .
      target: /app/fam_tools/

volumes:
  ai-integration-data: {}
