version: '3.3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ai_integration
    image: mariadb:10.2
    ports:
    - "3306:3306"
    volumes:
    - ai-integration-data:/var/lib/mysql
  web:
    environment:
      # RAILS_ENV: production # The startup script defaults to development, change to production if need be
      MYSQL_HOST: db
      MYSQL_PASSWORD: ai_integration
      FAMS_PASSCODE: aisupport
      FAMS_MAIN_USERNAME: ${FAMS_MAIN_USERNAME}
      FAMS_MAIN_PASSWORD: ${FAMS_MAIN_PASSWORD}
      FAMS_WEBSERVICES_USERNAME: ${FAMS_WEBSERVICES_USERNAME}
      FAMS_WEBSERVICES_PASSWORD: ${FAMS_WEBSERVICES_PASSWORD}
      FAMS_BACKUPS_SERVICE_USERNAME: ${FAMS_BACKUPS_SERVICE_USERNAME}
      FAMS_BACKUPS_SERVICE_PASSWORD: ${FAMS_BACKUPS_SERVICE_PASSWORD}
      FAMS_METADATA_DB_KEY: ${FAMS_METADATA_DB_KEY}
      FAMS_S3_BUCKET_API_KEY: ${FAMS_S3_BUCKET_API_KEY}
      FAMS_LP_SFTP_USERNAME: ${FAMS_LP_SFTP_USERNAME}
      FAMS_LP_SFTP_HOST: ${FAMS_LP_SFTP_HOST}
      FAMS_AI_CREATE_USER_API: ${FAMS_AI_CREATE_USER_API}
    build: 
      args:
        UID: "${UID:-1001}"
      context: .
      target: dev 
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
    - db
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      consistency: cached
      source: .
      target: /app/
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1400
volumes:
  ai-integration-data: {}
