version: '3.2'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ai_integration
      MYSQL_HOST: localhost
    image: mariadb:10.2
    ports:
    - "3306:3306"
    volumes:
    - ai-integration-data:/var/lib/mysql
  web:
    environment:
      MYSQL_HOST: db
      RAILS_ENV: development
    build:
      context: .
      args:
        RAILS_ENV: development
    command: >
      sh -c "echo starting database migrations &&
            rails db:create &&
            rails db:migrate &&
            rails s"
    ports:
    - "3000:3000"
    depends_on:
    - db

volumes:
  ai-integration-data:
