version: '3.2'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ai_integration
    image: mariadb:10.2
    ports:
    - "3306:3306"
    volumes:
    - ai-integration-data:/var/lib/mysql
  web:
    environment:
      MYSQL_HOST: db
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - db
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      consistency: cached
      source: .
      target: /fams_tools/

volumes:
  ai-integration-data:
