version: '3.3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ai_integration
    image: mariadb:10.3
    ports:
    - "3306:3306"
    volumes:
    - ai-integration-data:/var/lib/mysql
  web:
    environment:
      # RAILS_ENV: production # The startup script defaults to development, change to production if need be
      MYSQL_HOST: db
      MYSQL_PASSWORD: ai_integration 
    build: 
      context: .
      target: dev 
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
    - db
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      consistency: cached
      source: .
      target: /app/
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1400
volumes:
  ai-integration-data: {}
