version: '3.2'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ai_integration
    image: mariadb:10.3
    ports:
    - "3306:3306"
    volumes:
    - ai-integration-data:/var/lib/mysql
  web:
    image: app:latest
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: ai_integration
      RAILS_ENV: development
    # build: .
    build: 
      context: .
      dockerfile: Dockerfile.new
    ports:
    - "3000:3000"
    depends_on:
    - db
    stdin_open: true
    tty: true
    volumes:
    - type: bind
      consistency: cached
      source: .
      target: /app/fam_tools/

volumes:
  ai-integration-data: {}
