version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Rename Configs"
          command: |
            mv config/activity_insight.yml.circleci config/activity_insight.yml &&
            mv config/database.yml.circleci config/database.yml &&
            mv config/integration_passcode.yml.circleci config/integration_passcode.yml

      - run:
          name: "Build Container"
          command: |
            docker-compose build

      - run:
          name: "Rubocop"
          command: |
            docker-compose run web "bundle exec rubocop"

      - run:
          name: "Rspec"
          command: |
            docker-compose run web "RAILS_ENV=test bundle exec rspec"
