version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Container"
          command: |
            docker-compose build
