version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: "Build Container"
          command: |
            docker-compose build

      - run:
          name: "Rubocop"
          command: |
            docker-compose run web "bundle exec rubocop"

      - run:
          name: "Rspec"
          command: |
            docker-compose run web "RAILS_ENV=test bundle exec rspec"
