version: 2.1

jobs:
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - run:
          name: "Build Container"
          command: |
            docker-compose build
