version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Setup Files and Directories"
          command: |
            mv config/activity_insight.yml.circleci config/activity_insight.yml &&
            mv config/database.yml.circleci config/database.yml &&
            mv config/integration_passcode.yml.circleci config/integration_passcode.yml &&
            mkdir app/parsing_files &&
            mkdir public/psu

      - run:
          name: "Build Container"
          command: |
            docker-compose build

      - run:
          name: "Run Container"
          command: |
            docker-compose up -d

#      - run:
#          name: "Rubocop"
#          command: |
#            docker-compose exec web bundle exec rubocop

      - run:
          name: "Rspec"
          command: |
            docker-compose exec web bundle exec rspec
