development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URI") { "redis://localhost:6379/1" } %>
  channel_prefix: <% ENV.fetch("CHANNEL_PREFIX") { "ai_integration_production" } %>
