default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>
  port: 3306

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") { "ai_integration" } %>

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") { "ai_integration" } %>_test